# 実際には Node を使うが、Objective-C を指定することで OS X 環境で動かすようにする
language: objective-c
cache:
  directories:
    - node_modules
env:
  # Node はコマンドを個別に実行してインストールするため、ここでバージョンを指定する
  - NODE_VERSION="9.3"
before_install:
  # nvm をインストールする。Travis の OS X 環境には nvm はデフォルトで入っていない
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  # 指定バージョンの Node をインストールする
  - nvm install $NODE_VERSION
  # 指定バージョンの Node を有効にする
  - nvm use --delete-prefix $NODE_VERSION
  - node --version
install:
  - npm install
script:
  - npm test
before_deploy:
  # brew は最新状態にする
  - brew update
  # Windows環境へのビルドのために Wine は必須
  - brew install wine
  - wine --version
  # Windowsインストーラ作成のために makensis は必須
  - brew install makensis
  # ビルド + インストーラ作成 + zip化 までを各プラットフォームに対して行う
  - npm run archive
deploy:
  provider: releases
  # GitHub にリリースするための API KEY を暗号化した値
  api_key:
    secure: HVPCBrcQGWVykQPLVX7xMX8LZ1KOcNWSyQNFNbFHkKjUW2tfsH29f0ocIhse7OfRfFJ2jDD9sjKAzVyv6D/xigEamxCTqKvCky0P/HdQx18d74pLfXocZGtDFMJtpgpKvQbz1HLd96F30SQmygYSMOdZgGW8cT+L0nG92OW2kMgoKX2j+AlM+ubMpjs6g9dvnXww7ShYi3IdgXLiFE0rA6qIdKeEpq1lsNTRgNQDe9ZQcH7JOqgK/eNNS1mIqZfuWMRgli0DRFQNaH/AypOVM5RFtanJzXXgQN5BfcxFYR62PKeZ5jrYujhIEScQ4UcehGvhiwMRNMB/T9zSCacv353hZMQlE+eDhyorj3vKxG/cAgb6jMALHeGxBcTIhM88PHh3lq2CV50zItoCL5oDI85xakMreLXjaHyfJ0gacy+3fkB3iohPHqLZIhw+2xUudwyPA8og0n4umnXnc3t076MxA3mty0GTDkcpgpGxttCosRMzYbNh9LPYooIQEEzz/F679Vt5LTmCxsM/l1AuWs/1DqifSOKy8jyD9gFyquAQNqZ4GJCwt6WQpMetJNduGp8/l9p9KdU0qxuJrM7+TQ5BqT59uopN+d8XQC2Tkzc8BPOL6+W0iT8vLcCDihb7VHm4OZjMIGSs7ExemlTeM988Qq/y2fXNk7xsdLSsFs8=
  
  # Windowsのビルド環境は作ってはいるが、今はMacのみ対応
  file:  dist/osx/Markdown-Editor-osx.zip
  skip_cleanup: true
  on:
    repo: tadaken3/markdown-editor
    tags: true
    all_branches: true
